# Generated by Django 5.1.1 on 2024-11-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='attractions',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='city',
            name='average_climate',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='city',
            name='best_visit_season',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='city',
            name='description',
            field=models.TextField(default='Descripción no disponible'),
        ),
    ]
