# Generated by Django 5.1.1 on 2024-11-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_city_attractions_city_average_climate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='attractions',
        ),
        migrations.RemoveField(
            model_name='city',
            name='average_climate',
        ),
        migrations.RemoveField(
            model_name='city',
            name='best_visit_season',
        ),
        migrations.RemoveField(
            model_name='city',
            name='description',
        ),
        migrations.AddField(
            model_name='city',
            name='atracciones',
            field=models.CharField(blank=True, help_text='Atracciones turísticas', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='clima_promedio',
            field=models.CharField(blank=True, help_text='Clima\xa0promedio', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Breve descripción de la ciudad', null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='mejor_epoca_para_visitar',
            field=models.CharField(blank=True, help_text='Mejor época para visitar', max_length=50, null=True),
        ),
    ]
