# Generated by Django 5.1.1 on 2024-11-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_alter_city_clima_promedio'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen de la ciudad', null=True, upload_to='ciudades/'),
        ),
    ]
