# Generated by Django 5.1.1 on 2024-11-15 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_city_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='imagen',
        ),
    ]
